# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v0.6.0-116-ga996276
_src_path: https://github.com/usnistgov/cookiecutter-nist-python.git
command_line_interface: none
conda_channel: wpk-nist
email: wpk@nist.gov
full_name: William P. Krekelberg
github_username: usnistgov
project_name: module-utilities
project_short_description: Collection of utilities to aid working with python modules.
project_slug: module_utilities
pypi_username: wpk-nist
sphinx_theme: sphinx_book_theme
sphinx_use_autodocsumm: true
year: '2023'
