# need this to pick up requires-python from pyproject.toml
# extend = "./pyproject.toml"
extend-include = [
    "*.ipynb",
]
extend-exclude = [
    ".numba_cache",
    ".venv",
    "dist-conda",
    # "tests/",
    # "src/testpackage_book_nocli/tests",
    "src/module_utilities/vendored",
]
fix = true
# unsafe-fixes = true

[format]
docstring-code-format = true

[lint]
preview = true
select = [
    "ALL",
]
# fixable = ["ALL"]
unfixable = [
    "ERA",
    "PLR6104",
    "T",
]
ignore = [
    "ANN401",  # - Any ok sometimes
    "COM",     # - flake8-commas, formatter should take care of this?
    "CPY",     # - Don't require copyright
    "D105",    # - Missing magic method docstring
    "D107",    # - Missing docstring in __init__
    "D203",    # - 1 blank line required before class docstring
    "D205",    # - blank line after summary
    "D212",    # - Multi-line docstring summary should start at the first line
    "D400",    # - First line should end with a period
    "D401",    # - First line of docstring should be in imperative mood: "{first_line}"
    "DOC201",  # - Missing return from documentation
    "DOC501",  # - Missing raises from documentation
    "E501",    # - line too long - let formatter fix this
    "E731",    # - do not assign a lambda expression, use a def
    "FBT",     # - bools are ok
    "S404",    # - Want to use subprocess sometimes
    "S603",    # - subprocess-without-shell-equals-true
    "S607",    # - start-process-with-partial-path
    "PLC0415", # - import should be at top level (leads to issues with imports in func?)
    "TID252",  # - Allow relative imports
]
# Use extend-ignore for project specific ignores. Prefer lint.extend-per-file-ignores."src/**/*.py" below
# extend-ignore = [ ]
isort.known-first-party = [
    "module_utilities",
]
pydocstyle.convention = "numpy"
pylint.max-args = 15
pylint.max-positional-args = 15
pylint.max-public-methods = 30

[lint.per-file-ignores]
"docs/conf.py" = [
    "ERA",    # - Some helpful commented out code in conf.py
    "INP001", # - Namespace package fine for docs
]
"noxfile.py" = [
    "RUF009", # - Allow `add_option` for DataClassParser
]
"tests/*.py" = [
    "D",    # - Don't need to document tests
    "S101", # - Assert is fine with tests
]

# Project specific ignores (avoid changing per-file-ignores directly)
# extend-per-file-ignores."path/to/file.py" = [ ... ]
[lint.extend-per-file-ignores]
"**/*.ipynb" = [
    "ANN",
    "ARG001",
    "ARG002",
    "D101",
    "D102",
    "D103",
    "F811",
    "PLR6301",
    "S101",
    "SLF001",
    "T201",
]
"src/**/*.py" = [
    "NPY",    # - not using numpy?
    "SLF001", # - flake8-self (private access sometimes OK)
    "PD",     # - not using pandas?
]
"tests/*.py" = [
    "ANN",
    "FURB118",
    "N801",
    "PLR2004",
    "PLR6301",
    "SLF001",
]
