channels:
  - conda-forge
dependencies:
  - python>=3.8
  - typing-extensions
  - pytest
  - python-xdist
  - pytest-cov
  - pytest-sugar
  - mypy
  - ipython
  - ipykernel
  - setuptools-scm
  - nox
  - ruamel.yaml
  - pip
  - pip:
      - pytest-accept
      - noxopt
